name: RDP_Server
on: 
  workflow_dispatch:
jobs:
  run-rdp:
    runs-on: windows-latest
    steps:
      - name: Create User
        run: |
          $pass = "Admin123456!"
          $sec = ConvertTo-SecureString $pass -AsPlainText -Force
          New-LocalUser -Name "GitHubUser" -Password $sec -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "GitHubUser"
      - name: Connect Tailscale
        run: |
          Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi -OutFile ts.msi
          Start-Process msiexec.exe -ArgumentList "/i", "ts.msi", "/quiet", "/norestart" -Wait
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4
      - name: Keep Alive
        run: while($true) { Start-Sleep -Seconds 60 }
